GOOGLE_ID = "409075045567-h9qk605fg9bglsl1fvtcp9c24ole9fhv.apps.googleusercontent.com"
GOOGLE_SECRET = "lq9cIYFB2QPJgc8FIWTyu-LW"
SECRET_KEY = "development_secret"
MONGO_URI = "mongodb://localhost:27017/data"

WHITELIST = {
    "matthewaturner@tamu.edu",
    "Masonharris123@tamu.edu",
    "noahdsimp@tamu.edu",
    "patflores13@tamu.edu",
    "michaelmoe@tamu.edu",
    "garrett.hummel19@tamu.edu",
    "mkettler33@tamu.edu",
    "nmanning7@tamu.edu",
    "wcary@tamu.edu",
    "hlm837@tamu.edu",
    "kishk96@tamu.edu",
    "dclovej@tamu.edu",
    "mrbeef1@tamu.edu",
    "jameshaas15@tamu.edu",
    "drutledge15@tamu.edu",
    "jaredarend@tamu.edu",
    "johnbuettner@tamu.edu",
    "Tbartz13_1997@tamu.edu",
    "e.j.hardin@tamu.edu",
    "kress_ml@tamu.edu",
    "kylesnell@tamu.edu",
    "orchard.kyle@tamu.edu",
    "drew8700@tamu.edu",
    "colins@tamu.edu",
    "mitchflowers30@tamu.edu",
    "ljdorman20@tamu.edu",
    "stevenkyle96@tamu.edu",
    "mstefek98@tamu.edu",
    "hhbautista95@tamu.edu",
    "tylerwooten@tamu.edu",
    "evankonda@tamu.edu",
    "dsdotson@tamu.edu",
    "alvarez2529@tamu.edu",
    "isaacshrand@tamu.edu",
    "jacksulli21@tamu.edu",
    "cmangini509235@tamu.edu",
    "duncangraber@tamu.edu",
    "mday2@tamu.edu",
    "bradleydean97@tamu.edu",
    "crodriguez1212@tamu.edu",
    "alexander14@tamu.edu",
    "joseph15college@tamu.edu",
    "dfritcher@tamu.edu",
    "ejyoung11@tamu.edu",
    "czr96@tamu.edu",
    "shockleytamu@tamu.edu",
    "jonathanmcguire1@tamu.edu",
    "kudakwashe@tamu.edu",
    "jnojek13@tamu.edu",
    "haydenbowen96@tamu.edu",
    "jggaona0310@tamu.edu",
    "thriples@tamu.edu",
    "tngroves14@tamu.edu",
    "tjq85@tamu.edu",
    "cfau94@tamu.edu",
    "lsaucedo@tamu.edu",
    "rxtodd@tamu.edu"
}